# Generated by Django 3.1.5 on 2021-01-13 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stadup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.CharField(blank=True, max_length=100, null=True)),
                ('user_name', models.CharField(blank=True, max_length=100, null=True)),
                ('done', models.TextField(default='')),
                ('todo', models.TextField(default='')),
                ('problems', models.TextField(default='')),
                ('publication', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
